### ISSUE TITLE
Schema description attribute is always filled out

### ISSUE THREAD

**Issue by AidanHally** [icellmobilsoft/openapi-jaxb#15]
I have a complexType xsd object that does not contain any top-level annotation or docmentation tags

`<xs:complexType name="ComplexObject">
      <xs:sequence>
            <xs:element name="element1" type="tns:Element1" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>The element1 description.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>`

When the Java DTO gets generated, however, the class-level schema tag's description attribute is populated with the class package path, seemingly as a default when a description is not defined in the xsd.

 `@Schema(name = "ComplexObject", description = "complexobjectpath.ComplexObject")`

How can I leave the description blank in cases like this?

**Comment by petrenyi-mark** [comment]
Right now there is only a workaround for your case:
You can add `xsd:documentation` with a space:
```xsd
<xs:complexType name="ComplexObject"> 
    <xs:annotation> 
        <xs:documentation> </xs:documentation>
    </xs:annotation>
    <xs:sequence>
        <xs:element name="element1" type="tns:Element1" minOccurs="0" maxOccurs="unbounded"> 
            <xs:annotation> 
                <xs:documentation>The element1 description.</xs:documentation>
            </xs:annotation>
        </xs:element>
    </xs:sequence>
</xs:complexType>
```
The generated schema will be
```java
@Schema(name = "ComplexObject", description = " " )
```

Nevertheless I think the issue is valid, putting the package is might not the best option for description; still i dont't think leaving it empty would be a good idea. Would it work for you if we use the name as description if there isn't any `xsd:documentation` present?
```java
@Schema(name = "ComplexObject", description = "ComplexObject" )
```

**Comment by AidanHally** [comment]
So it would be nice to have the option to leave the description blank.

 In my case I have a number of endpoints that are labelled with a verb and a noun, "Create Host" for example. The xsd file defines the Create Host request body which will end up in the API documentation. In this case the documentation page will already be labelled with "Create Host" and below it you will see the request body object. It doesn't need a description as it is obvious as to what it is, and a if a description was added it could only be something along the lines if "The Request Body Object" or "This is the object you populate to create the host" which seems redundant and contrived . So yes, in some cases the option to leave the description blank would be welcomed.

Unfortunately the workaround doesn't have an effect on the outputted description. At the very least I need to put in a period to avoid having the full path produced. 

` <xs:annotation>
            <xs:documentation>. </xs:documentation>
        </xs:annotation>`

`@Schema(name = "compobj", description = ". ")`
